"""
Comprehensive neighborhood data + competition + land comps for PATTON.
"""

COMPETITION = {
    "Allapattah": [
        {"name": "Allapattah 17", "dev": "Related Group", "type": "Mixed-Use Rental", "units": 192, "status": "Under Construction",
         "delivery": "Q3 2025", "stories": 12, "unit_mix": {"Studio": 38, "1BR": 82, "2BR": 58, "3BR": 14},
         "sizes": {"Studio": 450, "1BR": 680, "2BR": 1050, "3BR": 1350},
         "rents": {"Studio": 1800, "1BR": 2400, "2BR": 3200, "3BR": 4100},
         "amenities": ["Rooftop Pool", "Fitness Center", "Co-Working", "Package Lockers", "Bike Storage", "Dog Park"],
         "rooftop": True, "parking": "1.0/unit", "psf_sale": None, "psf_rent": 3.52},
        {"name": "Lucía Allapattah", "dev": "Mast Capital", "type": "Condo", "units": 120, "status": "Pre-Construction",
         "delivery": "Q1 2026", "stories": 8, "unit_mix": {"1BR": 40, "2BR": 55, "3BR": 25},
         "sizes": {"1BR": 720, "2BR": 1100, "3BR": 1450},
         "rents": None,
         "amenities": ["Pool", "Gym", "Lobby Lounge", "Summer Kitchen", "Children's Play"],
         "rooftop": False, "parking": "1.5/unit", "psf_sale": 380, "psf_rent": None},
        {"name": "The Julia", "dev": "Lissette Calderon", "type": "Rental", "units": 323, "status": "Completed",
         "delivery": "2023", "stories": 14, "unit_mix": {"Studio": 65, "1BR": 130, "2BR": 97, "3BR": 31},
         "sizes": {"Studio": 420, "1BR": 650, "2BR": 980, "3BR": 1280},
         "rents": {"Studio": 1750, "1BR": 2300, "2BR": 3000, "3BR": 3800},
         "amenities": ["Rooftop Pool & Deck", "Fitness Center", "Co-Working Space", "Package Room", "Pet Spa", "BBQ Area"],
         "rooftop": True, "parking": "0.75/unit", "psf_sale": None, "psf_rent": 3.45},
    ],
    "Coconut Grove": [
        {"name": "Mr. C Residences", "dev": "Cipriani / Arquitectonica", "type": "Luxury Condo", "units": 118, "status": "Completed",
         "delivery": "2023", "stories": 21, "unit_mix": {"2BR": 45, "3BR": 50, "4BR": 18, "PH": 5},
         "sizes": {"2BR": 1500, "3BR": 2200, "4BR": 3400, "PH": 5500},
         "rents": None,
         "amenities": ["Bayfront Pool", "Spa & Wellness", "Private Marina", "Cipriani Restaurant", "Wine Cellar", "Children's Center", "Rooftop Observatory"],
         "rooftop": True, "parking": "2.0/unit", "psf_sale": 950, "psf_rent": None},
        {"name": "Arbor Residences", "dev": "Starwood Capital", "type": "Boutique Condo", "units": 52, "status": "Selling",
         "delivery": "Q4 2025", "stories": 8, "unit_mix": {"2BR": 20, "3BR": 24, "4BR": 8},
         "sizes": {"2BR": 1650, "3BR": 2400, "4BR": 3600},
         "rents": None,
         "amenities": ["Pool", "Fitness", "Garden Courtyard", "Concierge", "Summer Kitchen"],
         "rooftop": False, "parking": "2.0/unit", "psf_sale": 850, "psf_rent": None},
    ],
    "Wynwood": [
        {"name": "Wynwood Plaza", "dev": "L&L Holding / Carpe Real Estate", "type": "Mixed-Use", "units": 509, "status": "Under Construction",
         "delivery": "Q2 2025", "stories": 29, "unit_mix": {"Studio": 100, "1BR": 210, "2BR": 150, "3BR": 49},
         "sizes": {"Studio": 480, "1BR": 720, "2BR": 1150, "3BR": 1500},
         "rents": {"Studio": 2200, "1BR": 3000, "2BR": 4200, "3BR": 5500},
         "amenities": ["Rooftop Pool & Lounge", "Fitness Center", "Co-Working", "Retail Ground Floor", "Dog Park", "Art Gallery", "Juice Bar"],
         "rooftop": True, "parking": "0.75/unit", "psf_sale": None, "psf_rent": 4.50},
        {"name": "Arlo Wynwood", "dev": "Tricera Capital", "type": "Condo", "units": 198, "status": "Selling",
         "delivery": "Q3 2025", "stories": 8, "unit_mix": {"Studio": 40, "1BR": 88, "2BR": 55, "3BR": 15},
         "sizes": {"Studio": 440, "1BR": 680, "2BR": 1050, "3BR": 1380},
         "rents": None,
         "amenities": ["Pool", "Gym", "Lobby Bar", "BBQ Terrace", "Bike Storage"],
         "rooftop": False, "parking": "1.0/unit", "psf_sale": 560, "psf_rent": None},
    ],
    "Brickell": [
        {"name": "Baccarat Residences", "dev": "Related Group", "type": "Ultra-Luxury Condo", "units": 324, "status": "Under Construction",
         "delivery": "Q4 2025", "stories": 75, "unit_mix": {"1BR": 60, "2BR": 120, "3BR": 90, "4BR": 40, "PH": 14},
         "sizes": {"1BR": 900, "2BR": 1500, "3BR": 2400, "4BR": 3800, "PH": 7000},
         "rents": None,
         "amenities": ["5 Pools", "Full-Service Spa", "Private Cinema", "Wine Vault", "Cigar Room", "Children's Center", "Rooftop Sky Lounge", "Concierge 24/7", "Valet"],
         "rooftop": True, "parking": "2.0/unit", "psf_sale": 1200, "psf_rent": None},
        {"name": "Lofty Brickell", "dev": "Newgard Development", "type": "Condo", "units": 364, "status": "Selling",
         "delivery": "Q1 2026", "stories": 44, "unit_mix": {"Studio": 80, "1BR": 140, "2BR": 100, "3BR": 44},
         "sizes": {"Studio": 400, "1BR": 650, "2BR": 1000, "3BR": 1350},
         "rents": None,
         "amenities": ["Rooftop Pool", "Fitness", "Co-Working", "Theatre", "Pet Grooming", "EV Charging"],
         "rooftop": True, "parking": "1.0/unit", "psf_sale": 620, "psf_rent": None},
    ],
    "Little Havana": [
        {"name": "Calle 8 Residences", "dev": "Terra Group", "type": "Rental", "units": 210, "status": "Completed",
         "delivery": "2024", "stories": 8, "unit_mix": {"Studio": 45, "1BR": 95, "2BR": 55, "3BR": 15},
         "sizes": {"Studio": 400, "1BR": 620, "2BR": 950, "3BR": 1200},
         "rents": {"Studio": 1600, "1BR": 2100, "2BR": 2800, "3BR": 3500},
         "amenities": ["Pool", "Gym", "Community Room", "Package Lockers", "Bike Storage"],
         "rooftop": False, "parking": "0.5/unit", "psf_sale": None, "psf_rent": 3.20},
    ],
    "Overtown": [
        {"name": "Block 55", "dev": "Overtown CRA / Related", "type": "Mixed-Income Rental", "units": 434, "status": "Under Construction",
         "delivery": "Q4 2025", "stories": 12, "unit_mix": {"1BR": 180, "2BR": 175, "3BR": 79},
         "sizes": {"1BR": 650, "2BR": 950, "3BR": 1250},
         "rents": {"1BR": 1800, "2BR": 2500, "3BR": 3200},
         "amenities": ["Pool", "Fitness", "Community Room", "After-School Center", "Retail"],
         "rooftop": False, "parking": "0.5/unit", "psf_sale": None, "psf_rent": 2.70},
    ],
    "Flagler / West Flagler": [
        {"name": "858 Flagler Mixed-Use", "dev": "Private Developer", "type": "Condo/Retail", "units": 24, "status": "Pre-Construction",
         "delivery": "Q2 2026", "stories": 5, "unit_mix": {"1BR": 10, "2BR": 10, "3BR": 4},
         "sizes": {"1BR": 700, "2BR": 1050, "3BR": 1350},
         "rents": None,
         "amenities": ["Rooftop Terrace", "Fitness Room", "Ground Floor Retail", "Bike Storage"],
         "rooftop": True, "parking": "1.0/unit", "psf_sale": 420, "psf_rent": None},
    ],
    "Westchester": [],
    "Edgewater": [
        {"name": "Edition Residences", "dev": "Two Roads Development", "type": "Luxury Condo", "units": 185, "status": "Under Construction",
         "delivery": "Q2 2026", "stories": 55, "unit_mix": {"1BR": 35, "2BR": 75, "3BR": 55, "4BR": 15, "PH": 5},
         "sizes": {"1BR": 850, "2BR": 1400, "3BR": 2200, "4BR": 3500, "PH": 6000},
         "rents": None,
         "amenities": ["Bayfront Pool", "Full Spa", "Private Cinema", "Wine Room", "Rooftop Lounge", "Concierge", "Dog Park"],
         "rooftop": True, "parking": "2.0/unit", "psf_sale": 900, "psf_rent": None},
    ],
    "Downtown Miami": [
        {"name": "Miami Worldcenter — Phase 2", "dev": "Art Falcone / Nitin Motwani", "type": "Mixed-Use Condo", "units": 600, "status": "Under Construction",
         "delivery": "Q4 2026", "stories": 55, "unit_mix": {"Studio": 120, "1BR": 240, "2BR": 180, "3BR": 60},
         "sizes": {"Studio": 450, "1BR": 700, "2BR": 1100, "3BR": 1500},
         "rents": None,
         "amenities": ["Rooftop Pool & Sky Deck", "Fitness", "Co-Working", "Retail Promenade", "Concierge", "Dog Park"],
         "rooftop": True, "parking": "1.0/unit", "psf_sale": 550, "psf_rent": None},
    ],
}

LAND_COMPS = {
    "Allapattah": [
        {"addr": "2100 NW 22nd Ave", "lot_sf": 8500, "sale_price": 680000, "date": "2024-08", "zoning": "T5-O", "psf_land": 80, "buyer": "Private Developer"},
        {"addr": "1950 NW 20th St", "lot_sf": 12000, "sale_price": 960000, "date": "2024-06", "zoning": "T5-O", "psf_land": 80, "buyer": "Mast Capital"},
        {"addr": "NW 17th Ave & 21st", "lot_sf": 5500, "sale_price": 385000, "date": "2024-04", "zoning": "T4-R", "psf_land": 70, "buyer": "Local Investor"},
        {"addr": "2300 NW 23rd St", "lot_sf": 15000, "sale_price": 1275000, "date": "2024-02", "zoning": "T5-L", "psf_land": 85, "buyer": "Related Group"},
    ],
    "Coconut Grove": [
        {"addr": "3200 Shipping Ave", "lot_sf": 22000, "sale_price": 6600000, "date": "2024-09", "zoning": "T4-R", "psf_land": 300, "buyer": "Starwood Capital"},
        {"addr": "2890 SW 27th Ave", "lot_sf": 12000, "sale_price": 4200000, "date": "2024-05", "zoning": "T3-R", "psf_land": 350, "buyer": "Private"},
    ],
    "Little Havana": [
        {"addr": "1401 SW 1st St", "lot_sf": 7500, "sale_price": 525000, "date": "2024-10", "zoning": "T5-O", "psf_land": 70, "buyer": "Terra Group"},
        {"addr": "SW 7th St & 14th Ave", "lot_sf": 10000, "sale_price": 750000, "date": "2024-07", "zoning": "T5-O", "psf_land": 75, "buyer": "Private Dev"},
        {"addr": "801 SW 4th Ave", "lot_sf": 6000, "sale_price": 480000, "date": "2024-03", "zoning": "T4-R", "psf_land": 80, "buyer": "Local Investor"},
    ],
    "Wynwood": [
        {"addr": "2550 NW 2nd Ave", "lot_sf": 10000, "sale_price": 4500000, "date": "2024-09", "zoning": "T6-O NRD-1", "psf_land": 450, "buyer": "Tricera Capital"},
        {"addr": "NW 24th & 3rd", "lot_sf": 7500, "sale_price": 3000000, "date": "2024-06", "zoning": "T5-O NRD-1", "psf_land": 400, "buyer": "Moishe Mana"},
    ],
    "Brickell": [
        {"addr": "1400 S Miami Ave", "lot_sf": 30000, "sale_price": 45000000, "date": "2024-07", "zoning": "T6-80", "psf_land": 1500, "buyer": "Related Group"},
    ],
    "Overtown": [
        {"addr": "1500 NW 1st Ct", "lot_sf": 12000, "sale_price": 720000, "date": "2024-10", "zoning": "T6-O", "psf_land": 60, "buyer": "CRA Partnership"},
        {"addr": "NW 3rd Ave & 14th", "lot_sf": 8000, "sale_price": 440000, "date": "2024-05", "zoning": "T5-O", "psf_land": 55, "buyer": "Private Dev"},
        {"addr": "1601 NW 1st Ave", "lot_sf": 20000, "sale_price": 1200000, "date": "2024-02", "zoning": "T6-O", "psf_land": 60, "buyer": "Block 55 Partners"},
    ],
    "Flagler / West Flagler": [
        {"addr": "920 W Flagler St", "lot_sf": 6500, "sale_price": 455000, "date": "2024-09", "zoning": "T5-L", "psf_land": 70, "buyer": "Private"},
        {"addr": "SW 2nd St & 12th", "lot_sf": 8000, "sale_price": 520000, "date": "2024-06", "zoning": "T4-R", "psf_land": 65, "buyer": "Local Dev"},
    ],
    "Westchester": [
        {"addr": "9900 SW 40th Terr", "lot_sf": 7000, "sale_price": 350000, "date": "2024-07", "zoning": "EU-S", "psf_land": 50, "buyer": "Private"},
    ],
    "Edgewater": [
        {"addr": "420 NE 31st St", "lot_sf": 15000, "sale_price": 9000000, "date": "2024-08", "zoning": "T6-24", "psf_land": 600, "buyer": "Two Roads Dev"},
    ],
    "Downtown Miami": [
        {"addr": "NE 2nd Ave & 11th", "lot_sf": 25000, "sale_price": 10000000, "date": "2024-06", "zoning": "T6-48", "psf_land": 400, "buyer": "Worldcenter JV"},
    ],
}

DEV_RECOMMENDATIONS = {
    "Allapattah": {
        "best_product": "Mid-Rise Mixed-Use Rental (8-12 stories)",
        "rationale": "Highest rental yields in urban core with strong institutional demand. OZ designation favors long-term hold. Rental outperforms condo at current price points — buyer pool is still thin for >$400K condos in this submarket.",
        "unit_mix_rec": {"Studio": 15, "1BR": 40, "2BR": 35, "3BR": 10},
        "target_sizes": {"Studio": "400-480 sqft", "1BR": "620-720 sqft", "2BR": "950-1100 sqft", "3BR": "1200-1350 sqft"},
        "target_rents": {"Studio": "$1,700-$1,900", "1BR": "$2,200-$2,600", "2BR": "$3,000-$3,400", "3BR": "$3,800-$4,200"},
        "amenity_must": ["Rooftop Pool & Deck", "Fitness Center", "Co-Working/WFH Pods", "Package Lockers", "Bike Storage"],
        "amenity_diff": ["Art Gallery/Exhibition Space", "Community Garden", "Pet Spa", "Juice/Coffee Bar"],
        "rooftop_rec": "YES — Essential. Every new competitor has rooftop. Without it, 15-20% rent discount.",
        "parking_rec": "0.75-1.0 per unit. Area is transit-adjacent; over-parking increases cost without proportional rent premium.",
        "target_buyer": "Young professionals 25-38, healthcare workers (Jackson), artists/creatives. Median income $35-55K.",
        "construction": {"type": "Type IIIA Wood-Frame over Podium", "cost_psf": "$180-$220", "timeline": "18-24 months"},
        "comp_advantage": "Price 5-10% below Wynwood for equivalent product. Leverage arts district narrative without Wynwood premium.",
    },
    "Coconut Grove": {
        "best_product": "Low-Rise Boutique Condo (4-8 stories)",
        "rationale": "Premium market demands exclusivity. Low density zoning (T3/T4) limits supply = value protection. Buyer pool is affluent, design-conscious, and willing to pay for privacy and green space.",
        "unit_mix_rec": {"2BR": 35, "3BR": 45, "4BR": 15, "PH": 5},
        "target_sizes": {"2BR": "1,500-1,800 sqft", "3BR": "2,200-2,800 sqft", "4BR": "3,200-4,000 sqft", "PH": "4,500-6,000 sqft"},
        "target_rents": None,
        "amenity_must": ["Pool", "Fitness Center", "Concierge", "Landscaped Gardens", "Covered Parking"],
        "amenity_diff": ["Private Wine Storage", "Summer Kitchen per Unit", "EV Charging", "Yoga/Meditation Garden"],
        "rooftop_rec": "OPTIONAL — Ground-level pool with lush landscaping preferred for Grove aesthetic. Rooftop observatory for views.",
        "parking_rec": "2.0 per unit minimum. Suburban-feel buyers expect covered parking.",
        "target_buyer": "Established professionals 38-60, families, international buyers (LatAm). Household income $120K+.",
        "construction": {"type": "Type I Concrete", "cost_psf": "$300-$400", "timeline": "24-30 months"},
        "comp_advantage": "Boutique scale (under 60 units) with Grove village walkability. Cannot compete on height — compete on exclusivity.",
    },
    "Wynwood": {
        "best_product": "Mid-Rise Mixed-Use (Retail + Residential, 8-15 stories)",
        "rationale": "NRD-1 allows high FAR. Ground-floor retail commands $60-80/sqft NNN. Residential above benefits from global brand recognition. Condo or rental both viable — condo for faster exit, rental for OZ hold.",
        "unit_mix_rec": {"Studio": 20, "1BR": 40, "2BR": 30, "3BR": 10},
        "target_sizes": {"Studio": "440-520 sqft", "1BR": "680-780 sqft", "2BR": "1,050-1,200 sqft", "3BR": "1,380-1,550 sqft"},
        "target_rents": {"Studio": "$2,100-$2,400", "1BR": "$2,800-$3,300", "2BR": "$3,800-$4,500", "3BR": "$5,000-$5,800"},
        "amenity_must": ["Rooftop Pool & Sky Lounge", "State-of-Art Fitness", "Co-Working", "Ground Floor Retail/F&B"],
        "amenity_diff": ["Art Curation Program", "Recording Studio", "Content Creation Room", "Rooftop Cinema"],
        "rooftop_rec": "YES — Non-negotiable. Must have skyline views. Budget $800K-$1.2M for rooftop build-out.",
        "parking_rec": "0.75/unit. Transit + walkability = reduced demand. Excess parking is dead cost.",
        "target_buyer": "Tech workers, digital nomads, creative professionals 28-42. Design-forward, experience-driven.",
        "construction": {"type": "Type IIIA or Type I (depending on height)", "cost_psf": "$220-$280", "timeline": "20-28 months"},
        "comp_advantage": "Ground-floor F&B/retail activation is key differentiator. Dead ground floor = failed project in Wynwood.",
    },
    "Brickell": {
        "best_product": "High-Rise Luxury Condo (40+ stories)",
        "rationale": "T6-80 allows maximum density. International buyer pool provides liquidity. Pre-sales fund construction. Branded residences command 30-40% premium.",
        "unit_mix_rec": {"1BR": 20, "2BR": 35, "3BR": 30, "4BR": 10, "PH": 5},
        "target_sizes": {"1BR": "800-1,000 sqft", "2BR": "1,400-1,600 sqft", "3BR": "2,200-2,800 sqft", "4BR": "3,500-4,500 sqft", "PH": "5,000-8,000 sqft"},
        "target_rents": None,
        "amenity_must": ["Multiple Pools", "Full Spa", "Fitness", "Concierge 24/7", "Valet Parking", "Children's Center"],
        "amenity_diff": ["Private Cinema", "Wine Vault", "Cigar Lounge", "Sky Lounge", "Golf Simulator"],
        "rooftop_rec": "YES — Sky lounge/amenity deck on upper floors is market standard. Multiple amenity levels expected.",
        "parking_rec": "1.5-2.0/unit. Valet operation preferred. EV charging 100% of spaces.",
        "target_buyer": "HNW international buyers (LatAm, Europe), finance professionals, C-suite. Household $200K+.",
        "construction": {"type": "Type I Reinforced Concrete", "cost_psf": "$350-$500", "timeline": "30-42 months"},
        "comp_advantage": "Brand partnership (hotel flag) is the #1 differentiator at this price point. Without it, compete on location/views.",
    },
    "Little Havana": {
        "best_product": "Low-Rise Multifamily Rental (4-6 stories)",
        "rationale": "Highest yields in core + OZ = build and hold 10+ years. Condo buyer pool too thin at current income levels. Small-scale is nimble — 20-40 unit buildings fill fast at these rents.",
        "unit_mix_rec": {"Studio": 10, "1BR": 45, "2BR": 35, "3BR": 10},
        "target_sizes": {"Studio": "380-430 sqft", "1BR": "600-680 sqft", "2BR": "900-1,000 sqft", "3BR": "1,150-1,250 sqft"},
        "target_rents": {"Studio": "$1,500-$1,700", "1BR": "$1,900-$2,200", "2BR": "$2,600-$3,000", "3BR": "$3,200-$3,600"},
        "amenity_must": ["Pool (even small)", "Fitness Room", "Package Lockers", "Bike Storage"],
        "amenity_diff": ["Community Kitchen", "Outdoor Movie Screen", "Cultural Programming Space"],
        "rooftop_rec": "NICE TO HAVE — Small rooftop terrace with skyline views toward Brickell adds $100-150/mo rent premium.",
        "parking_rec": "0.5/unit. High walk/transit scores. Structured parking too expensive for target rents.",
        "target_buyer": "Service workers, young professionals, students. Median income $28-40K.",
        "construction": {"type": "Type VA Wood-Frame", "cost_psf": "$160-$200", "timeline": "14-18 months"},
        "comp_advantage": "Speed to market. Small footprint = faster permits, faster construction, faster lease-up. Don't over-amenitize.",
    },
    "Overtown": {
        "best_product": "Mid-Rise Mixed-Income Rental (6-10 stories)",
        "rationale": "Strongest OZ + CRA incentives. Mixed-income model de-risks: affordable set-aside unlocks tax credits + 4% LIHTC. Market-rate units benefit from Health District adjacency.",
        "unit_mix_rec": {"1BR": 40, "2BR": 40, "3BR": 20},
        "target_sizes": {"1BR": "620-700 sqft", "2BR": "900-1,050 sqft", "3BR": "1,200-1,300 sqft"},
        "target_rents": {"1BR": "$1,600-$2,000", "2BR": "$2,200-$2,800", "3BR": "$2,800-$3,400"},
        "amenity_must": ["Pool", "Fitness", "Community Room", "After-School/Tutoring Space"],
        "amenity_diff": ["Health & Wellness Programming", "Job Training Center", "Urban Garden"],
        "rooftop_rec": "OPTIONAL — Budget-dependent. If included, keep simple (terrace + BBQ, no pool).",
        "parking_rec": "0.5/unit. High transit scores (Metrorail). Surface parking if possible to save cost.",
        "target_buyer": "Healthcare workers, essential workers, young families. Broad income range $25-60K.",
        "construction": {"type": "Type IIIA Wood over Podium", "cost_psf": "$170-$210", "timeline": "18-24 months"},
        "comp_advantage": "LIHTC + OZ + CRA triple stack. Financial engineering is the product — the building just needs to be solid and clean.",
    },
    "Flagler / West Flagler": {
        "best_product": "Townhome / Duplex-Triplex Conversion (2-4 stories)",
        "rationale": "Zoning supports duplex/triplex on most lots. Value-add renovation of existing stock delivers fastest ROI. New townhome product fills gap between aging SFR and downtown condos.",
        "unit_mix_rec": {"2BR": 40, "3BR": 50, "4BR": 10},
        "target_sizes": {"2BR": "1,000-1,200 sqft", "3BR": "1,350-1,600 sqft", "4BR": "1,800-2,200 sqft"},
        "target_rents": {"2BR": "$2,200-$2,600", "3BR": "$2,800-$3,200", "4BR": "$3,500-$4,000"},
        "amenity_must": ["Private Patio/Yard", "In-Unit W/D", "Covered Parking"],
        "amenity_diff": ["Rooftop Deck (per unit)", "Smart Home Package", "EV Charger"],
        "rooftop_rec": "PER-UNIT rooftop decks on townhomes add $200-300/mo rent or $30-50K sale premium. High ROI.",
        "parking_rec": "1.0/unit. On-site covered. Street parking supplements.",
        "target_buyer": "Young families, remote workers wanting space, Coral Gables overflow. Income $50-80K.",
        "construction": {"type": "Type VB Wood-Frame", "cost_psf": "$150-$190", "timeline": "12-16 months"},
        "comp_advantage": "Only new townhome product in the corridor. Gap in market between $400K SFR and $600K+ condo.",
    },
    "Westchester": {
        "best_product": "Single Family Renovation / ADU Addition",
        "rationale": "Zoning restricts multifamily. Best play is buy-renovate-rent or ADU (Accessory Dwelling Unit) where permitted. Cash flow play, not development play.",
        "unit_mix_rec": {"3BR": 60, "4BR": 30, "ADU/1BR": 10},
        "target_sizes": {"3BR": "1,500-1,800 sqft", "4BR": "2,000-2,400 sqft", "ADU/1BR": "400-600 sqft"},
        "target_rents": {"3BR": "$2,200-$2,600", "4BR": "$2,800-$3,200", "ADU/1BR": "$1,200-$1,500"},
        "amenity_must": ["Updated Kitchen", "Modern Bath", "Hurricane Impact Windows", "Covered Parking"],
        "amenity_diff": ["Pool", "Smart Home", "Solar Panels"],
        "rooftop_rec": "N/A — Single-story residential area. Not applicable.",
        "parking_rec": "Driveway + garage. Standard suburban.",
        "target_buyer": "Families, FIU faculty/staff, first-time buyers. Income $45-70K.",
        "construction": {"type": "Renovation / CBS Addition", "cost_psf": "$100-$150", "timeline": "4-8 months"},
        "comp_advantage": "Lowest risk strategy. Buy below replacement cost, renovate to modern standard, hold for cash flow.",
    },
    "Edgewater": {
        "best_product": "High-Rise Waterfront Condo (20-40 stories)",
        "rationale": "Bay views are the product. T6 zoning allows density. Compete on views and proximity to both Wynwood and Design District.",
        "unit_mix_rec": {"1BR": 25, "2BR": 40, "3BR": 25, "PH": 10},
        "target_sizes": {"1BR": "750-900 sqft", "2BR": "1,200-1,500 sqft", "3BR": "1,800-2,400 sqft", "PH": "3,500-5,000 sqft"},
        "target_rents": None,
        "amenity_must": ["Bayfront Pool", "Spa", "Fitness", "Concierge", "Dog Park"],
        "amenity_diff": ["Rooftop Sky Bar", "Paddle Board/Kayak Launch", "Outdoor Yoga Deck"],
        "rooftop_rec": "YES — Bay-view sky lounge is key selling point. Must capitalize on panoramic views.",
        "parking_rec": "1.5/unit. Garage with EV charging.",
        "target_buyer": "Young professionals, international buyers, design-conscious couples. Income $80K+.",
        "construction": {"type": "Type I Concrete", "cost_psf": "$280-$380", "timeline": "28-36 months"},
        "comp_advantage": "Bayfront at lower PSF than Brickell. Target buyers priced out of Brickell but wanting waterfront.",
    },
    "Downtown Miami": {
        "best_product": "Mid-Rise to High-Rise Mixed-Use (15-40 stories)",
        "rationale": "Transit hub (Brightline) drives demand. OZ in select tracts. Large-scale mixed-use with ground-floor retail/F&B.",
        "unit_mix_rec": {"Studio": 20, "1BR": 35, "2BR": 30, "3BR": 15},
        "target_sizes": {"Studio": "420-500 sqft", "1BR": "680-780 sqft", "2BR": "1,050-1,200 sqft", "3BR": "1,400-1,600 sqft"},
        "target_rents": {"Studio": "$1,900-$2,200", "1BR": "$2,500-$3,000", "2BR": "$3,400-$4,000", "3BR": "$4,500-$5,200"},
        "amenity_must": ["Rooftop Pool", "Fitness", "Co-Working", "Retail Ground Floor", "Package Room"],
        "amenity_diff": ["Sky Lounge", "Golf Simulator", "Pet Spa", "Podcast Studio"],
        "rooftop_rec": "YES — Skyline views are a primary selling point. Multi-level amenity deck recommended.",
        "parking_rec": "1.0/unit. Metromover access reduces demand.",
        "target_buyer": "Young urban professionals, Brightline commuters, remote workers. Income $50-90K.",
        "construction": {"type": "Type I Concrete or Type IIIA over Podium", "cost_psf": "$220-$320", "timeline": "24-36 months"},
        "comp_advantage": "Brightline adjacency is unique. Position as 'connected living' — 1hr to Fort Lauderdale, 3hr to Orlando.",
    },
}
